{{- define "common.secretProvider.tpl" -}}
{{- $top := first . }}
{{- $providers := index . 1 }}
{{- range $provider := $providers }}

---

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $provider.name | default (include "common.fullname" $top) }}
  {{- include "common.metadata" (list $top) | nindent 2 }}
spec:
    provider: vault
    secretObjects:
    {{- range $secret := $provider.secrets }}
    - secretName: {{ $secret.name }}
      type: Opaque
      data:
        {{- range $spec := $secret.specs }}
        - objectName: {{ $spec.objectName }}
          key: {{ $spec.objectName }}
        {{- end }}
    {{- end }}
    parameters:
      vaultAddress: {{ $provider.vaultAddress | default "http://vault:8200" }}
      roleName: {{ $provider.roleName | default (include "common.name" $top) }}
      objects: |
        {{- range $secret := $provider.secrets }}
        {{- range $spec := $secret.specs }}
        - objectName: {{ $spec.objectName | quote }}
          secretPath: {{ $spec.path | quote }}
          secretKey: {{ $spec.key | quote }}
        {{- end }}
        {{- end }}
{{- end }}
{{- end }}

{{- define "common.secretProvider" -}}
{{- include "common.utils.merge" (append . "common.secretProvider.tpl") }}
{{- end }}
