apiVersion: v2
name: rafiki-backend
description: Rafiki Backend Helm chart for Kubernetes
home: https://github.com/interledger/rafiki

type: application
version: 0.1.0
appVersion: "v1.0.0-alpha.5"

dependencies:
  - name: common
    version: 0.0.1
    repository: file://../common
    import-values:
      - child: securityContext
        parent: securityContext
      - child: podSecurityContext
        parent: podSecurityContext
  - name: redis
    version: "18.2.1"
    repository: "https://charts.bitnami.com/bitnami"

maintainers:
  - name: golobitch
    email: tadej.golobic@gatehub.net
  - name: enejm
    email: enej.mlinaric@gatehub.net
